--- 
author: nikosgram13
commands: 
  protection: 
    aliases: 
      - protect
      - protector
      - p
    description: "Access to Oglofus-Protection commands"
    permission: oglofus.protection.command
    usage: /<command>
description: "${project.description}"
main: me.nikosgram.oglofus.protection.bukkit.OglofusBukkit
name: "${project.name}"
version: "${project.version}"
