name: ${project.name}
version: ${project.version}
main: me.nikosgram.oglofus.protection.bukkit.OglofusBukkit
softdepend: [WorldEdit, WorldGuard]
description: ${project.description}
author: nikosgram13

commands:
    protection:
        description: Access to Oglofus-Protection commands
        aliases: [protect, protector, p]
        permission: oglofus.protection.command
        usage: /<command>